// <auto-generated />
namespace SistemaInventario.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class modelsupdate04nov202201 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(modelsupdate04nov202201));
        
        string IMigrationMetadata.Id
        {
            get { return "202211050253139_models-update-04nov2022-01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
